name: Pull Request Check

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    name: Node ${{ matrix.node_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [8, 10, 12]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Cloning repo
        uses: actions/checkout@v1
      - name: Using Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          version: ${{ matrix.node_version }}
      - name: npm ci, lint, and test
        run: |
          npm ci
          npm run eslint
          npm test
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
